### ISSUE TITLE
Run starts in wrong working directory

### ISSUE THREAD

**Issue by jackokring** [Ambez05/mcx16vscodeext#3]
A *LOAD "$", 1: LIST* does not display the project directory content but the vs code appdata directory. This makes code for getting files have an unreasonable cycle and a *cwd $dir* needs prepending to the emulator run command.

**Comment by Ambez05** [comment]
Will implement this in the next release,  should be about a week.  This should also have simple Intelesense.

**Comment by Ambez05** [comment]
New version has been published that fixes this issue(1.2).  Please close this issue if you are happy with this.

**Comment by jackokring** [comment]
ok, still not available as a market update, but sounds good.
